---

- name: Ensure presence of ~/.config/Code/User
  file:
    path: ~/.config/Code/User
    state: directory
    mode: "0775"

- name: Copy initial settings.json for vscode
  copy:
    src: vscode/settings.json
    dest: ~/.config/Code/User/settings.json
    mode: "0664"
    force: no
