---

- name: Ensure presence of ~/.gnupg
  file:
    path: ~/.gnupg
    state: directory
    mode: "0700"

- name: Place hardened gnupg configs
  copy:
    src: "{{ item }}"
    dest: "~/.gnupg/{{ item }}"
    mode: "0644"
  loop:
    - gpg.conf
    - gpg-agent.conf
